name: Harshie CI Build Test

on: [ push, pull_request ]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Harshie
        uses: actions/checkout@v3

      - name: Setup CMake and Install D++
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y wget libopus0
          wget -O dpp.deb https://dl.dpp.dev/
          sudo dpkg -i dpp.deb

      - name: Create .env
        env:
          ENCODED_CLIENT_TOKEN: ${{ secrets.ENCODED_CLIENT_TOKEN }}
        run: |
          echo "ENCODED_CLIENT_TOKEN=$ENCODED_CLIENT_TOKEN" > .env

      - name: Harshie Build Test
        run: |
          mkdir build
          cd build
          cmake ..
          make -j8

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout Harshie
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Create .env
        env:
          ENCODED_CLIENT_TOKEN: ${{ secrets.ENCODED_CLIENT_TOKEN }}
        run: |
          echo "ENCODED_CLIENT_TOKEN=$ENCODED_CLIENT_TOKEN" > .env

      - name: Harshie Build Test
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release
          
  premake-windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout Harshie
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.1

      - name: Premake setup
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Harshie Build Test
        run: |
          premake5 vs2022
          msbuild /m "Harshie.sln" /p:configuration="release"