name: CMake

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Harshie
        uses: actions/checkout@v3

      - name: Setup CMake and Install D++
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y wget
          wget -O dpp.deb https://dl.dpp.dev/
          sudo dpkg -i dpp.deb

      - name: Build Test
        run: |
          mkdir build
          cd build
          cmake ..
          make -j8